// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function AddCategory(name) {
    return $Call.ByID(1180544068, name);
}

/**
 * @param {string} name
 * @param {string} url
 * @returns {$CancellablePromise<void>}
 */
export function AddRepository(name, url) {
    return $Call.ByID(3049654672, name, url);
}

/**
 * BrowseLibrary scans all repo symbol directories and returns a flat list of imported parts.
 * @returns {$CancellablePromise<$models.LibraryPart[]>}
 */
export function BrowseLibrary() {
    return $Call.ByID(3817859458).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * CheckConflicts scans the target library locations and checks if any files with matching names already exist.
 * @param {string} filename
 * @param {string} category
 * @param {string} repoName
 * @returns {$CancellablePromise<string[]>}
 */
export function CheckConflicts(filename, category, repoName) {
    return $Call.ByID(2224678442, filename, category, repoName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function DeleteCategory(name) {
    return $Call.ByID(988551738, name);
}

/**
 * FindDuplicates checks if the incoming file's symbol already exists in any repo/category.
 * @param {string} filename
 * @returns {$CancellablePromise<$models.DuplicateInfo[]>}
 */
export function FindDuplicates(filename) {
    return $Call.ByID(2158640096, filename).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.Config>}
 */
export function GetConfig() {
    return $Call.ByID(1200034045).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @param {string} filename
 * @returns {$CancellablePromise<string>}
 */
export function GetItemSummary(filename) {
    return $Call.ByID(1278049696, filename);
}

/**
 * @param {string} filename
 * @returns {$CancellablePromise<string>}
 */
export function GuessCategory(filename) {
    return $Call.ByID(3867462498, filename);
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function HandleDroppedItem(path) {
    return $Call.ByID(3264139776, path);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function HideWindow() {
    return $Call.ByID(542966029);
}

/**
 * @param {string} filename
 * @param {string} category
 * @param {string} repoName
 * @param {string} conflictStrategy
 * @param {string} newName
 * @returns {$CancellablePromise<void>}
 */
export function ProcessFile(filename, category, repoName, conflictStrategy, newName) {
    return $Call.ByID(3913388868, filename, category, repoName, conflictStrategy, newName);
}

/**
 * RemoveRepository unlinks a repository from the app config without deleting files on disk.
 * @param {string} repoName
 * @returns {$CancellablePromise<void>}
 */
export function RemoveRepository(repoName) {
    return $Call.ByID(3806196213, repoName);
}

/**
 * @param {string} oldName
 * @param {string} newName
 * @returns {$CancellablePromise<void>}
 */
export function RenameCategory(oldName, newName) {
    return $Call.ByID(3179227807, oldName, newName);
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function SaveSetup(path) {
    return $Call.ByID(1847944557, path);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function SelectDirectory() {
    return $Call.ByID(1735672136);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function SelectWatchDirectory() {
    return $Call.ByID(2801046955);
}

/**
 * SetDefaultRepository marks a repository as the default import target.
 * @param {string} repoName
 * @returns {$CancellablePromise<void>}
 */
export function SetDefaultRepository(repoName) {
    return $Call.ByID(1926989872, repoName);
}

/**
 * @param {string} filename
 * @returns {$CancellablePromise<void>}
 */
export function SkipFile(filename) {
    return $Call.ByID(3914901836, filename);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function StartWatcher() {
    return $Call.ByID(1872299225);
}

/**
 * SyncAllRepositories runs git pull --rebase on every git-backed repository.
 * @returns {$CancellablePromise<void>}
 */
export function SyncAllRepositories() {
    return $Call.ByID(2668055061);
}

/**
 * ToggleAutoStart creates or removes a LaunchAgent plist in ~/Library/LaunchAgents/.
 * @param {boolean} enable
 * @returns {$CancellablePromise<void>}
 */
export function ToggleAutoStart(enable) {
    return $Call.ByID(1830522718, enable);
}

/**
 * UndoAction reverts a previously imported component
 * @param {string} id
 * @returns {$CancellablePromise<boolean>}
 */
export function UndoAction(id) {
    return $Call.ByID(2137951341, id);
}

// Private type creation functions
const $$createType0 = $models.LibraryPart.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = $models.DuplicateInfo.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $models.Config.createFrom;
