// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} name
 * @param {string} url
 * @returns {$CancellablePromise<void>}
 */
export function AddRepository(name, url) {
    return $Call.ByID(3049654672, name, url);
}

/**
 * @returns {$CancellablePromise<$models.Config>}
 */
export function GetConfig() {
    return $Call.ByID(1200034045).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} filename
 * @returns {$CancellablePromise<string>}
 */
export function GetItemSummary(filename) {
    return $Call.ByID(1278049696, filename);
}

/**
 * @param {string} filename
 * @returns {$CancellablePromise<string>}
 */
export function GuessCategory(filename) {
    return $Call.ByID(3867462498, filename);
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function HandleDroppedItem(path) {
    return $Call.ByID(3264139776, path);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function HideWindow() {
    return $Call.ByID(542966029);
}

/**
 * @param {string} filename
 * @param {string} category
 * @param {string} repoName
 * @returns {$CancellablePromise<void>}
 */
export function ProcessFile(filename, category, repoName) {
    return $Call.ByID(3913388868, filename, category, repoName);
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function SaveSetup(path) {
    return $Call.ByID(1847944557, path);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function SelectDirectory() {
    return $Call.ByID(1735672136);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function SelectWatchDirectory() {
    return $Call.ByID(2801046955);
}

/**
 * @param {string} filename
 * @returns {$CancellablePromise<void>}
 */
export function SkipFile(filename) {
    return $Call.ByID(3914901836, filename);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function StartWatcher() {
    return $Call.ByID(1872299225);
}

/**
 * UndoAction reverts a previously imported component
 * @param {string} id
 * @returns {$CancellablePromise<boolean>}
 */
export function UndoAction(id) {
    return $Call.ByID(2137951341, id);
}

// Private type creation functions
const $$createType0 = $models.Config.createFrom;
